### ISSUE TITLE
Join pop out window not working

### ISSUE THREAD

**Issue by Satori83** [joaomgcd/JoinChrome#120]
I noticed after updating Chrome now when I try to open Join in its own pop out window it doesn't do anything. Theres no Chrome error about it being blocked either.

**Comment by joaomgcd** [comment]
Which version of Chrome are you using?

**Comment by Satori83** [comment]
Version 102.0.5005.61 (Official Build) (arm64)

**Comment by joaomgcd** [comment]
Hhm, I just tried that on my Windows PC and it still works.. Is that on Linux? Mac?

**Comment by medlir** [comment]
I was having this issue on Windows 10 as well and I was getting an error in the inpect dev console for the extention about it being out of bounds.

Resolved by Chrome menu, More Tools, Extensions, Join, Details, Inspect Views, "join.html", Application tab in dev console, Local Storage, wiped out the popoutWidth and popoutHeight values, which allowed it to fall back on the default hard-coded values, and it successfully was able to open the popout immediately after nuking those.

**Comment by joaomgcd** [comment]
Oh, thanks for the tip. Seems like I need to try and fix that! Does that fix your issue though @Satori83 ?

**Comment by Satori83** [comment]
Interestingly enough one of Macbooks was working still, the other had the issue but following the steps listed to remove pop out values fixed it. Thanks guys!

**Comment by joaomgcd** [comment]
Glad it worked! :) Thanks for the input!

**Comment by clubtech** [comment]
@joaomgcd will you be releasing a fix for this? I'm still having this issue with version 1.8.23 of the extension.

**Comment by joaomgcd** [comment]
@clubtech did the solution mentioned above not work for you?

**Comment by clubtech** [comment]
> 
@joaomgcd it fixed it for me but would it be possible to release a permanent fix for this via the chrome store?

**Comment by joaomgcd** [comment]
Yes, I need to put out a permanent fix for this. Ideally the window should always be created in a usable space...

**Comment by Satori83** [comment]
Yes it worked for me. I thought I replied back to let you know.



Thanks,

Scott Foster


*Founder / Project Coordinator*

*Office: 215-550-1405 *

<http://upcity.com/local-marketing-agencies/profiles/satori-design>
<http://upcity.com/local-marketing-agencies/profiles/satori-design>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Satori Design is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.
